log:            "warning"
logger:         "syslog"
warnings:       0
show_errors:    0
route_cache:    1

# NEVER enable auto_reload in production
auto_reload:    0

maxlinks:       10
pages:          "/home/mike/pages"

